modLoader = "javafml"
loaderVersion = "[4,)"
license = "Custom"

[[mixins]]
config = "brewery-common.mixins.json"

[[mods]]
modId = "brewery"
version = "${version}"
displayName = "[Let's Do] Brewery"
authors = "satisfy"
credits = "MissLilitu, CR-055"
description = '''
Ozapft is! Brau Bier, beiss in a Bretzn – willkomme zum Braufescht!'''
logoFile = "pack.png"

[[dependencies.brewery]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brewery]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brewery]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.brewery]]
modId = "farm_and_charm"
mandatory = true
versionRange = "[1.1.0,)"
ordering = "AFTER"
side = "BOTH"